### ISSUE TITLE
Cannot disable emoij's, always in mail reading pane enabled

### ISSUE THREAD

**Issue by barrydegraaff** [ZeXtras/openchat-zimlet#1]
I am running Zimbra 8.7.9 with Zimbra chat open, even when I disable the emoijs in
the zimlet preferences, they still show in the mail reading pane, breaking code snippets
and putting smileys in invoices. 

Only disabling the entire zimlet, solves the problem.

**Comment by barrydegraaff** [comment]
@bud-mo this bug is still in Zimbra 8.8.4... I did not notice it before, so maybe it is re-introduced.

**Comment by barrydegraaff** [comment]
@ZxCine cc'ed for info.

**Comment by bud-mo** [comment]
Hi @barrydegraaff!
Can You please provide the commit You can found in the "About..." panel in the Preferences Dialog of OpenChat window?
(Is located near the Version, with the annotation Version @commit )

**Comment by barrydegraaff** [comment]
8.7.10
https://github.com/ZeXtras/openchat-zimlet/tree/ec495f6
@ec495f6

**Comment by barrydegraaff** [comment]
Seems like a version of may 12th is in 8.8.4 that does not has this fix... but maybe I interpret it wrong.
